console-table-printer/console-table-printer

- package-lock.json
- package.json
Fixing the version update that was not trigger in last build
> Fix: Update version of packages

- package-lock.json
- package.json
- src/internal-table-printer.ts
- src/internal-table.ts
- src/table-helpers.ts
- test/columnColor.test.ts
- feature: color all values in column
> feat: Column color

- package-lock.json
- package.json
- src/internalTable/internal-table-printer.ts
- src/utils/table-helpers.ts
When a value of a cell is 0 is was converted to ''
> Fix: 0 cell value as string

- index.ts
- package-lock.json
- package.json
- src/internalTable/internal-table-printer.ts
- src/internalTable/internal-table.ts
- src/utils/colored-console-line.ts
- src/utils/table-constants.ts
- src/utils/table-helpers.ts
- test/types.test.ts
- Types for COLOR and ALIGNMENT in Typescript
- Improved Test coverage to 100%
> feat: Types

- PULL_REQUEST_TEMPLATE.md
- README.md
- package-lock.json
- package.json
> chore: Documentation update

- README.md
- package-lock.json
- package.json
- src/console-table-printer.ts
- src/internalTable/internal-table.ts
- test/internalTable/rowColor.test.ts
- test/readmeExamples.test.ts
Fixes #212 
Summary of what this is about
Basically passing options in addRows doesnt work. This PR fixes it
> feat: Batch row coloring props

- README.md
- package-lock.json
- package.json
Adding dependency badges of David back
> chore: Add back david dependency badges

- package-lock.json
- package.json
The dependency bot was not updating the package-lock.json version. Now its updated
> fix: Updating Package Lock

- package-lock.json
- package.json
- src/utils/table-constants.ts
- src/utils/table-helpers.ts
> fix: linting issues

- package-lock.json
- package.json
- src/console-table-printer.ts
- src/internalTable/internal-table-printer.ts
- src/internalTable/internal-table.ts
- src/utils/colored-console-line.ts
- src/utils/table-helpers.ts
- test/columnColor.test.ts
- test/computedFunction.test.ts
- test/internalTable/alignment.test.ts
- test/internalTable/borderStyle.test.ts
- test/internalTable/columnColor.test.ts
- test/internalTable/computedColumn.test.ts
- test/internalTable/enableDisable.test.ts
- test/internalTable/filter.test.ts
- test/internalTable/rowColor.test.ts
- test/internalTable/simpleTable.test.ts
- test/internalTable/sorting.test.ts
- test/internalTable/title.test.ts
- test/readmeExamples.test.ts
- test/render.test.ts
This feature output the table as a string. You can output the string yourself to any other console that you have. This console can be also remote console.
This was asked as a feature here: https://github.com/ayonious/console-table-printer/issues/245
> feat: Table Render

- .releaserc.json
- .travis.yml
- README.md
- package-lock.json
- package.json
> feat(technical): semantic release

- .github/PULL_REQUEST_TEMPLATE.md
Updating PR template for github
> chore(technical): Update github PR template

- README.md
Readme has been updated further to talk about title in Header
> fix(docs): readme update for Header title

- test/internalTable/headerTitle.test.ts
> chore: small refactor

- package.json
- yarn.lock
> chore(deps): update all deps

- src/internalTable/internal-table-printer.ts
- src/internalTable/internal-table.ts
- src/models/external-table.ts
- src/models/internal-table.ts
- src/utils/table-constants.ts
Following coding style of all interface case
> chore(tech): code refactor

- src/utils/string-utils.ts
- test/__snapshots__/newLines.test.ts.snap
- test/newLines.test.ts
Fixes #438
New lines within a cell would put a new line through the whole table, breaking formatting.
```sh
┌────────────┬──────────────────────────────────────────┬──────────────────────────────────────────┐
│        foo │                   bar                    │ baz                                      │
├────────────┼──────────────────────────────────────────┼──────────────────────────────────────────┤
habitant morbi tristique senectus et netus et                      │ * Cras ac ligula aliquet, ultrices erat  │
│            │    malesuada fames ac turpis egestas.    │ quis, laoreet lorem.
* Mauris rutrum nisi et nisl                                          │
│            │ Maecenas ut scelerisque felis. Etiam ut  │ sollicitudin semper.
* Nunc laoreet felis auctor …
```
> fix: new lines in cells broke table format

- README.md
> chore: Update badges Update README.md

- README.md
Summary of what this is about
| Before | After |
| ------ | ----- |
| 🧟     | 😎    |
chore(deps): some dependency update
feat: Line Width is not limited, previously it was unlimited
fix(technical): Deployment issue with npm is fixed
fix: title names can be decorated
> chore: Add more badges

- .circleci/config.yml
> chore: Codecov support

- README.md
- package.json
> chore: change old git urls

- README.md
> chore: Codecov badge

- src/internalTable/internal-table-printer.test.ts
> chore: More codecov

- src/internalTable/internal-table.test.ts
> chore: Adding test with all possible options

- .github/workflows/code-quality.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/test-all-versions.yml
- .github/workflows/test-pack.yml
- package.json
Summary of what this is about
| Before | After |
| ------ | ----- |
| 🧟     | 😎    |
chore(deps): some dependency update
feat: Line Width is not limited, previously it was unlimited
fix(technical): Deployment issue with npm is fixed
fix: title names can be decorated
> chore: pack test

- src/models/external-table.ts
- test/performance/memoryLimit.test.ts
- test/performance/scalability.test.ts
Summary of what this is about
| Before | After |
| ------ | ----- |
| 🧟     | 😎    |
chore(deps): some dependency update
feat: Line Width is not limited, previously it was unlimited
fix(technical): Deployment issue with npm is fixed
fix: title names can be decorated
> fix: adding some docs regarding the types

- index.ts
- src/models/external-table.ts
- test/printTable.test.ts
https://github.com/console-table-printer/console-table-printer/issues/463
> fix: Better Types for calculated Column, sort, filter functions

- .github/workflows/code-quality.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/test-all-versions.yml
- .github/workflows/test-pack.yml
Upgrading all the git actions version to latest ones. This makes sure all the testing is done properly and with latest setup.
> chore: Upgrade all actions versions
